#!/bin/sh

./BUILD-qemuarm/sysroots/i686-linux/usr/bin/qemu-system-arm \
-kernel ./BUILD-qemuarm/deploy/images/zImage-qemuarm.bin \
-hda ./BUILD-qemuarm/deploy/images/webos-image-qemuarm.ext3 \
-net nic,vlan=0 -net tap,vlan=0,ifname=tap0,script=no,downscript=no \
-M versatilepb \
-m 128 \
--append "root=/dev/sda rw console=ttyAMA0,115200 console=tty ip=192.168.7.2::192.168.7.1:255.255.255.0 mem=128M highres=off "

