#!/bin/sh

MACHINE=`uname -m`
./BUILD-qemux86/sysroots/$MACHINE-linux/usr/bin/qemu \
-kernel ./BUILD-qemux86/deploy/images/bzImage-qemux86.bin \
-hda ./BUILD-qemux86/deploy/images/webos-image-qemux86.ext3 \
-net nic,vlan=0 -net tap,vlan=0,ifname=tap0,script=no,downscript=no \
-m 256 -vga vmware \
--append "vga=0 root=/dev/hda rw mem=256M ip=192.168.7.2::192.168.7.1:255.255.255.0 "
